"""SDK-CLIENT-22 - Account Deregistration and Deletion UX tests.

Covers section20 test strategy: command parsing, preflight, transport,
async lifecycle, proof, negative, model, and repair guidance tests.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Any, Dict
from unittest.mock import MagicMock, patch

import pytest

from keyhole_sdk.deregister.models import (
    DeregistrationOutcome,
    DeregistrationRequest,
    DeregistrationStatus,
)
from keyhole_sdk.deregister.errors import (
    DeregistrationAlreadyDeletedError,
    DeregistrationError,
    DeregistrationNetworkError,
    DeregistrationNotAuthenticatedError,
    DeregistrationOwnershipMismatchError,
    DeregistrationPolicyBlockedError,
    DeregistrationSurfaceUnavailableError,
)
from keyhole_sdk.deregister.client import DeregistrationClient
from keyhole_sdk.deregister.proof import DeregistrationProofBundle


# --------------------------------------------------------------
# section20.1 - Model tests
# --------------------------------------------------------------


class TestDeregistrationRequest:
    """DeregistrationRequest deterministic serialisation."""

    def test_to_run_payload_shape(self):
        req = DeregistrationRequest(
            registration_id="user-abc",
            confirm=True,
            realm="kh-prod",
        )
        payload = req.to_run_payload()
        assert payload["run_type"] == "auth.remove"
        assert payload["parameters"]["user_id"] == "user-abc"
        assert payload["parameters"]["realm"] == "kh-prod"
        assert payload["parameters"]["confirm"] is True

    def test_to_proof_dict_no_secrets(self):
        req = DeregistrationRequest(
            registration_id="user-abc",
            realm="kh-dev",
            correlation_id="corr-123",
        )
        proof = req.to_proof_dict()
        assert proof["registration_id"] == "user-abc"
        assert proof["realm"] == "kh-dev"
        assert proof["correlation_id"] == "corr-123"
        # No tokens, passwords, or secrets
        for key in proof:
            assert "token" not in key.lower()
            assert "password" not in key.lower()
            assert "secret" not in key.lower()

    def test_correlation_id_autogenerated(self):
        req = DeregistrationRequest(registration_id="user-abc")
        assert req.correlation_id is not None
        assert len(req.correlation_id) > 0

    def test_default_realm_is_kh_prod(self):
        req = DeregistrationRequest(registration_id="user-abc")
        assert req.realm == "kh-prod"


class TestDeregistrationStatus:
    """DeregistrationStatus enum values - section14."""

    def test_required_statuses_exist(self):
        assert DeregistrationStatus.ACCEPTED == "accepted"
        assert DeregistrationStatus.DEFERRED == "deferred"
        assert DeregistrationStatus.REPLAYED == "replayed"
        assert DeregistrationStatus.REJECTED == "rejected"
        assert DeregistrationStatus.ALREADY_DELETED == "already_deleted"
        assert DeregistrationStatus.FAILED == "failed"
        assert DeregistrationStatus.TRANSPORT_ERROR == "transport_error"

    def test_all_status_values_are_strings(self):
        for status in DeregistrationStatus:
            assert isinstance(status.value, str)


class TestDeregistrationOutcome:
    """DeregistrationOutcome status mapping - section18."""

    def test_accepted_outcome(self):
        outcome = DeregistrationOutcome(
            status=DeregistrationStatus.ACCEPTED,
            registration_id="user-abc",
            run_id="run-123",
            correlation_id="corr-456",
        )
        assert outcome.status == DeregistrationStatus.ACCEPTED
        assert outcome.registration_id == "user-abc"
        assert outcome.run_id == "run-123"

    def test_normalise_removed_true(self):
        """Server returns removed=True -> maps to ACCEPTED."""
        outcome = DeregistrationOutcome.model_validate({
            "removed": True,
            "registration_id": "user-abc",
        })
        assert outcome.status == DeregistrationStatus.ACCEPTED

    def test_normalise_lifecycle_state_removed(self):
        """Server returns lifecycle_state=removed -> maps to ACCEPTED."""
        outcome = DeregistrationOutcome.model_validate({
            "lifecycle_state": "removed",
            "registration_id": "user-abc",
        })
        assert outcome.status == DeregistrationStatus.ACCEPTED

    def test_normalise_identity_not_found(self):
        """Server returns identity_not_found -> maps to ALREADY_DELETED."""
        outcome = DeregistrationOutcome.model_validate({
            "error": "identity_not_found",
            "registration_id": "user-abc",
        })
        assert outcome.status == DeregistrationStatus.ALREADY_DELETED

    def test_safe_summary_proof_safe(self):
        outcome = DeregistrationOutcome(
            status=DeregistrationStatus.REJECTED,
            registration_id="user-abc",
            reason="ownership mismatch",
            repair_guidance=["Log in as the account owner."],
        )
        summary = outcome.safe_summary()
        assert summary["status"] == "rejected"
        assert summary["registration_id"] == "user-abc"
        assert summary["reason"] == "ownership mismatch"
        assert "Log in as the account owner." in summary["repair_guidance"]

    def test_outcome_with_no_optional_fields(self):
        outcome = DeregistrationOutcome(
            status=DeregistrationStatus.FAILED,
            registration_id="user-xyz",
        )
        assert outcome.run_id is None
        assert outcome.reason is None
        assert outcome.repair_guidance == []


# --------------------------------------------------------------
# section20.2 - Error class tests
# --------------------------------------------------------------


class TestDeregistrationErrors:
    """Error classes have correct slugs and repair suggestions - section19."""

    def test_base_error(self):
        err = DeregistrationError("test error")
        assert err.error_class == "deregistration_error"
        assert err.reason == "test error"

    def test_not_authenticated_error(self):
        err = DeregistrationNotAuthenticatedError()
        assert err.error_class == "deregistration_not_authenticated"
        assert "keyhole login" in err.repair_suggestions[0].lower()

    def test_ownership_mismatch_error(self):
        err = DeregistrationOwnershipMismatchError(
            acting_id="user-a", target_id="user-b",
        )
        assert err.error_class == "deregistration_ownership_mismatch"
        assert "user-a" in str(err)
        assert "user-b" in str(err)
        assert any("account owner" in s.lower() for s in err.repair_suggestions)

    def test_surface_unavailable_error(self):
        err = DeregistrationSurfaceUnavailableError()
        assert err.error_class == "deregistration_surface_unavailable"
        assert any("boundary" in s.lower() for s in err.repair_suggestions)

    def test_policy_blocked_error(self):
        err = DeregistrationPolicyBlockedError()
        assert err.error_class == "deregistration_policy_blocked"
        assert any("support" in s.lower() for s in err.repair_suggestions)

    def test_already_deleted_error(self):
        err = DeregistrationAlreadyDeletedError()
        assert err.error_class == "deregistration_already_deleted"
        assert any("prior" in s.lower() for s in err.repair_suggestions)

    def test_network_error(self):
        err = DeregistrationNetworkError()
        assert err.error_class == "deregistration_network_error"
        assert any("network" in s.lower() for s in err.repair_suggestions)

    def test_all_errors_inherit_from_base(self):
        """All error classes inherit from DeregistrationError."""
        errors = [
            DeregistrationNotAuthenticatedError(),
            DeregistrationOwnershipMismatchError(),
            DeregistrationSurfaceUnavailableError(),
            DeregistrationPolicyBlockedError(),
            DeregistrationAlreadyDeletedError(),
            DeregistrationNetworkError(),
        ]
        for err in errors:
            assert isinstance(err, DeregistrationError)

    def test_all_errors_have_repair_suggestions(self):
        """Every error class provides at least one repair suggestion."""
        errors = [
            DeregistrationNotAuthenticatedError(),
            DeregistrationOwnershipMismatchError(),
            DeregistrationSurfaceUnavailableError(),
            DeregistrationPolicyBlockedError(),
            DeregistrationAlreadyDeletedError(),
            DeregistrationNetworkError(),
        ]
        for err in errors:
            assert len(err.repair_suggestions) > 0, f"{err.error_class} has no repair"


# --------------------------------------------------------------
# section20.3 - Transport tests (client dispatch)
# --------------------------------------------------------------


class TestDeregistrationClientTransport:
    """Deletion uses governed transport with correct headers - section14."""

    def _mock_response(
        self,
        status_code: int = 200,
        json_data: dict | None = None,
    ) -> MagicMock:
        resp = MagicMock()
        resp.status_code = status_code
        resp.json.return_value = json_data or {
            "ok": True,
            "data": {
                "removed": True,
                "user_id": "user-abc",
                "lifecycle_state": "removed",
            },
        }
        return resp

    @patch("keyhole_sdk.deregister.client.requests.post")
    def test_dispatch_uses_runs_start(self, mock_post):
        """Deletion goes through POST /mcp/v1/runs (not DELETE /auth/account)."""
        mock_post.return_value = self._mock_response()
        client = DeregistrationClient(mcp_base_url="https://mcp.test.com")
        req = DeregistrationRequest(registration_id="user-abc")
        client.deregister(req, access_token="tok-123")

        call_args = mock_post.call_args
        url = call_args[0][0] if call_args[0] else call_args[1].get("url", "")
        if not url:
            url = str(call_args)
        assert "/mcp/v1/runs" in url
        assert "DELETE" not in str(call_args).upper() or "/auth/account" not in url

    @patch("keyhole_sdk.deregister.client.requests.post")
    def test_request_id_header_attached(self, mock_post):
        """X-Request-Id is present in the request - section14."""
        mock_post.return_value = self._mock_response()
        client = DeregistrationClient(mcp_base_url="https://mcp.test.com")
        req = DeregistrationRequest(registration_id="user-abc")
        client.deregister(req, access_token="tok-123")

        headers = mock_post.call_args[1]["headers"]
        assert "X-Request-Id" in headers
        assert len(headers["X-Request-Id"]) > 0

    @patch("keyhole_sdk.deregister.client.requests.post")
    def test_idempotency_key_header_attached(self, mock_post):
        """X-Idempotency-Key is present in the request - section14."""
        mock_post.return_value = self._mock_response()
        client = DeregistrationClient(mcp_base_url="https://mcp.test.com")
        req = DeregistrationRequest(registration_id="user-abc")
        client.deregister(req, access_token="tok-123")

        headers = mock_post.call_args[1]["headers"]
        assert "X-Idempotency-Key" in headers
        assert len(headers["X-Idempotency-Key"]) > 0

    @patch("keyhole_sdk.deregister.client.requests.post")
    def test_authorization_header_attached(self, mock_post):
        """Bearer token is present in the request."""
        mock_post.return_value = self._mock_response()
        client = DeregistrationClient(mcp_base_url="https://mcp.test.com")
        req = DeregistrationRequest(registration_id="user-abc")
        client.deregister(req, access_token="tok-123")

        headers = mock_post.call_args[1]["headers"]
        assert headers["Authorization"] == "Bearer tok-123"

    @patch("keyhole_sdk.deregister.client.requests.post")
    def test_run_type_is_auth_remove(self, mock_post):
        """Run type dispatched is 'auth.remove' - exact key."""
        mock_post.return_value = self._mock_response()
        client = DeregistrationClient(mcp_base_url="https://mcp.test.com")
        req = DeregistrationRequest(registration_id="user-abc")
        client.deregister(req, access_token="tok-123")

        payload = mock_post.call_args[1]["json"]
        assert payload["run_type"] == "auth.remove"

    @patch("keyhole_sdk.deregister.client.requests.post")
    def test_network_error_raises_typed_exception(self, mock_post):
        """Network failures raise DeregistrationNetworkError."""
        from requests.exceptions import ConnectionError
        mock_post.side_effect = ConnectionError("refused")
        client = DeregistrationClient(mcp_base_url="https://mcp.test.com")
        req = DeregistrationRequest(registration_id="user-abc")
        with pytest.raises(DeregistrationNetworkError):
            client.deregister(req, access_token="tok-123")


# --------------------------------------------------------------
# section20.4 - Async lifecycle tests (outcome classification)
# --------------------------------------------------------------


class TestDeregistrationOutcomeClassification:
    """Outcome classification - section18."""

    def test_accepted_from_removed_true(self):
        outcome = DeregistrationClient._classify_outcome(
            status_code=200,
            data={"removed": True, "lifecycle_state": "removed"},
            registration_id="user-abc",
            correlation_id="corr-1",
        )
        assert outcome.status == DeregistrationStatus.ACCEPTED

    def test_already_deleted_from_identity_not_found(self):
        outcome = DeregistrationClient._classify_outcome(
            status_code=200,
            data={"error": "identity_not_found"},
            registration_id="user-abc",
            correlation_id="corr-1",
        )
        assert outcome.status == DeregistrationStatus.ALREADY_DELETED
        assert "not found" in outcome.reason.lower()

    def test_rejected_from_4xx(self):
        outcome = DeregistrationClient._classify_outcome(
            status_code=403,
            data={"message": "Forbidden", "error": "unauthorized"},
            registration_id="user-abc",
            correlation_id="corr-1",
        )
        assert outcome.status == DeregistrationStatus.REJECTED

    def test_failed_from_5xx(self):
        outcome = DeregistrationClient._classify_outcome(
            status_code=500,
            data={"error": "internal_error"},
            registration_id="user-abc",
            correlation_id="corr-1",
        )
        assert outcome.status == DeregistrationStatus.FAILED
        assert "500" in outcome.reason

    def test_accepted_from_200_default(self):
        """200 without explicit markers -> ACCEPTED."""
        outcome = DeregistrationClient._classify_outcome(
            status_code=200,
            data={"run_id": "run-xyz"},
            registration_id="user-abc",
            correlation_id="corr-1",
        )
        assert outcome.status == DeregistrationStatus.ACCEPTED
        assert outcome.run_id == "run-xyz"

    def test_outcome_preserves_correlation_id(self):
        outcome = DeregistrationClient._classify_outcome(
            status_code=200,
            data={"removed": True},
            registration_id="user-abc",
            correlation_id="corr-specific",
        )
        assert outcome.correlation_id == "corr-specific"


# --------------------------------------------------------------
# section20.5 - Proof tests
# --------------------------------------------------------------


class TestDeregistrationProofBundle:
    """Proof artifacts created deterministically - section17."""

    def test_generate_contains_all_required_files(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(
            request={"registration_id": "user-abc", "realm": "kh-prod"},
            outcome={"status": "accepted", "run_id": "run-123"},
            identity_snapshot={"user_id": "acting-user"},
            success=True,
        )
        expected_files = [
            "core.json", "request.json", "response.json",
            "identity_snapshot.json", "event_chain.json",
            "correlation.json", "repair.json", "summary.md", "digest.txt",
        ]
        for f in expected_files:
            assert f in bundle, f"Missing proof artifact: {f}"

    def test_core_contains_story_id(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(success=False)
        assert bundle["core.json"]["story_id"] == "SDK-CLIENT-22"

    def test_core_contains_proof_type(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(success=True)
        assert bundle["core.json"]["proof_type"] == "deregistration"

    def test_identity_snapshot_preserved(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        identity = {"user_id": "act-user", "tenant_id": "tenant-1"}
        bundle = proof.generate(identity_snapshot=identity, success=True)
        assert bundle["identity_snapshot.json"]["user_id"] == "act-user"

    def test_registration_id_preserved(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(
            request={"registration_id": "user-target"},
            success=True,
        )
        assert bundle["request.json"]["registration_id"] == "user-target"

    def test_run_id_linkage_captured(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(
            outcome={"status": "accepted", "run_id": "run-xyz"},
            success=True,
        )
        assert bundle["correlation.json"]["run_id"] == "run-xyz"

    def test_rejection_includes_repair_guidance(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(
            outcome={
                "status": "rejected",
                "reason": "ownership mismatch",
                "repair_guidance": ["Log in as the account owner."],
            },
            success=False,
        )
        assert bundle["repair.json"]["reason"] == "ownership mismatch"
        assert "Log in as the account owner." in bundle["repair.json"]["repair_guidance"]

    def test_digest_is_sha256(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle = proof.generate(success=True)
        assert bundle["digest.txt"].startswith("sha256:")

    def test_write_creates_files_on_disk(self, tmp_path):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        proof.record_event("test_event", {"detail": "test"})
        bundle_dir = proof.write(
            request={"registration_id": "user-abc"},
            outcome={"status": "accepted"},
            success=True,
            output_dir=tmp_path,
        )
        assert bundle_dir.exists()
        assert (bundle_dir / "core.json").exists()
        assert (bundle_dir / "request.json").exists()
        assert (bundle_dir / "summary.md").exists()
        assert (bundle_dir / "digest.txt").exists()

    def test_write_path_is_identity_scoped(self, tmp_path):
        """Proof path is <output_dir>/deregister/<correlation-id>/ - section17."""
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        bundle_dir = proof.write(success=True, output_dir=tmp_path)
        assert "deregister" in str(bundle_dir)
        assert "corr-123" in str(bundle_dir)

    def test_event_chain_records_events(self):
        proof = DeregistrationProofBundle(correlation_id="corr-123")
        proof.record_event("dispatched", {"target": "user-abc"})
        proof.record_event("outcome", {"status": "accepted"})
        bundle = proof.generate(success=True)
        events = bundle["event_chain.json"]["events"]
        assert len(events) == 2
        assert events[0]["event_type"] == "dispatched"
        assert events[1]["event_type"] == "outcome"


# --------------------------------------------------------------
# section20.1 - Command parsing / CLI deregister function tests
# --------------------------------------------------------------


class TestDeregisterCommandParsing:
    """CLI command function invocation - section20.1."""

    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_missing_auth_returns_failure(self, mock_store_cls):
        """Unauthenticated deletion attempt is blocked locally - section20.2."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_store = MagicMock()
        mock_store.load.return_value = None
        mock_store_cls.return_value = mock_store

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        assert result.success is False
        assert "not authenticated" in result.summary.lower()
        assert any("login" in s.lower() for s in result.next_steps)

    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_expired_session_returns_failure(self, mock_store_cls):
        """Expired session is blocked locally."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_session = MagicMock()
        mock_session.is_expired = True
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        assert result.success is False
        assert "expired" in result.summary.lower()

    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_confirmation_required_without_yes(self, mock_store_cls):
        """Confirmation is required when --yes is absent - section20.2."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_session = MagicMock()
        mock_session.is_expired = False
        mock_session.access_token = "tok"
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        result = run_deregister(
            registration_id="user-abc",
            yes=False,  # no confirmation
            mcp_url="https://mcp.test.com",
        )
        assert result.success is False
        assert "confirmation" in result.summary.lower()
        assert any("--yes" in s for s in result.next_steps)

    @patch("keyhole_cli.commands.deregister.DeregistrationClient")
    @patch("keyhole_cli.commands.deregister.WhoamiClient")
    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_successful_dispatch_returns_accepted(
        self, mock_store_cls, mock_whoami_cls, mock_dereg_cls
    ):
        """Accepted deletion renders correctly - section20.4."""
        from keyhole_cli.commands.deregister import run_deregister

        # Mock session
        mock_session = MagicMock()
        mock_session.is_expired = False
        mock_session.access_token = "tok"
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        # Mock whoami
        mock_whoami = MagicMock()
        mock_whoami.user_id = "user-abc"
        mock_whoami.tenant_id = "tenant-1"
        mock_whoami.org_id = "org-1"
        mock_whoami.mode.value = "governed"
        mock_whoami.display_name = "Test User"
        mock_whoami_cls.return_value.whoami.return_value = mock_whoami

        # Mock deregistration
        mock_outcome = DeregistrationOutcome(
            status=DeregistrationStatus.ACCEPTED,
            registration_id="user-abc",
            run_id="run-xyz",
            correlation_id="corr-123",
        )
        mock_dereg_cls.return_value.deregister.return_value = mock_outcome

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        assert result.success is True
        assert result.data["status"] == "accepted"
        assert "run-xyz" in str(result.data.get("run_id", ""))

    @patch("keyhole_cli.commands.deregister.DeregistrationClient")
    @patch("keyhole_cli.commands.deregister.WhoamiClient")
    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_rejected_dispatch_returns_failure_with_guidance(
        self, mock_store_cls, mock_whoami_cls, mock_dereg_cls
    ):
        """Rejected deletion renders with repair guidance - section18.3."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_session = MagicMock()
        mock_session.is_expired = False
        mock_session.access_token = "tok"
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        mock_whoami = MagicMock()
        mock_whoami.user_id = "other-user"
        mock_whoami.tenant_id = "t"
        mock_whoami.org_id = "o"
        mock_whoami.mode.value = "governed"
        mock_whoami.display_name = None
        mock_whoami_cls.return_value.whoami.return_value = mock_whoami

        mock_outcome = DeregistrationOutcome(
            status=DeregistrationStatus.REJECTED,
            registration_id="user-abc",
            reason="ownership mismatch",
            repair_guidance=["Log in as the account owner."],
        )
        mock_dereg_cls.return_value.deregister.return_value = mock_outcome

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        assert result.success is False
        assert result.data["status"] == "rejected"


# --------------------------------------------------------------
# section20.6 - Negative tests
# --------------------------------------------------------------


class TestDeregisterNegative:
    """Negative paths - section20.6."""

    @patch("keyhole_cli.commands.deregister.DeregistrationClient")
    @patch("keyhole_cli.commands.deregister.WhoamiClient")
    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_network_error_returns_failure(
        self, mock_store_cls, mock_whoami_cls, mock_dereg_cls
    ):
        """Network error produces typed failure."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_session = MagicMock()
        mock_session.is_expired = False
        mock_session.access_token = "tok"
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        mock_whoami = MagicMock()
        mock_whoami.user_id = "user-abc"
        mock_whoami.tenant_id = "t"
        mock_whoami.org_id = "o"
        mock_whoami.mode.value = "governed"
        mock_whoami.display_name = None
        mock_whoami_cls.return_value.whoami.return_value = mock_whoami

        mock_dereg_cls.return_value.deregister.side_effect = (
            DeregistrationNetworkError("Connection refused")
        )

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        assert result.success is False
        assert result.data["error_class"] == "deregistration_network_error"

    @patch("keyhole_cli.commands.deregister.DeregistrationClient")
    @patch("keyhole_cli.commands.deregister.WhoamiClient")
    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_client_never_claims_deleted_when_only_accepted(
        self, mock_store_cls, mock_whoami_cls, mock_dereg_cls
    ):
        """Client does not claim 'deleted' when server said 'accepted' - section20.6."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_session = MagicMock()
        mock_session.is_expired = False
        mock_session.access_token = "tok"
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        mock_whoami = MagicMock()
        mock_whoami.user_id = "user-abc"
        mock_whoami.tenant_id = "t"
        mock_whoami.org_id = "o"
        mock_whoami.mode.value = "governed"
        mock_whoami.display_name = None
        mock_whoami_cls.return_value.whoami.return_value = mock_whoami

        mock_outcome = DeregistrationOutcome(
            status=DeregistrationStatus.ACCEPTED,
            registration_id="user-abc",
            run_id="run-123",
        )
        mock_dereg_cls.return_value.deregister.return_value = mock_outcome

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        # Must NOT say "deleted successfully" - only "accepted"
        summary = result.summary.lower()
        assert "deleted successfully" not in summary
        assert "accepted" in summary or "deletion accepted" in summary

    @patch("keyhole_cli.commands.deregister.DeregistrationClient")
    @patch("keyhole_cli.commands.deregister.WhoamiClient")
    @patch("keyhole_cli.commands.deregister.CredentialStore")
    def test_already_deleted_renders_correctly(
        self, mock_store_cls, mock_whoami_cls, mock_dereg_cls
    ):
        """Already-deleted is a no-op, not a new destructive mutation - section18.4."""
        from keyhole_cli.commands.deregister import run_deregister

        mock_session = MagicMock()
        mock_session.is_expired = False
        mock_session.access_token = "tok"
        mock_store = MagicMock()
        mock_store.load.return_value = mock_session
        mock_store_cls.return_value = mock_store

        mock_whoami = MagicMock()
        mock_whoami.user_id = "user-abc"
        mock_whoami.tenant_id = "t"
        mock_whoami.org_id = "o"
        mock_whoami.mode.value = "governed"
        mock_whoami.display_name = None
        mock_whoami_cls.return_value.whoami.return_value = mock_whoami

        mock_outcome = DeregistrationOutcome(
            status=DeregistrationStatus.ALREADY_DELETED,
            registration_id="user-abc",
            reason="Not found",
            repair_guidance=["Inspect the prior deletion outcome."],
        )
        mock_dereg_cls.return_value.deregister.return_value = mock_outcome

        result = run_deregister(
            registration_id="user-abc",
            yes=True,
            mcp_url="https://mcp.test.com",
        )
        assert result.success is True  # already deleted is not a failure
        assert "already deleted" in result.summary.lower()


# --------------------------------------------------------------
# Surface negotiation integration - evaluator tests
# --------------------------------------------------------------


class TestDeregisterSurfaceNegotiation:
    """keyhole deregister is registered in the evaluator - section10."""

    def test_deregister_in_command_requirements(self):
        from keyhole_sdk.negotiation.evaluator import COMMAND_REQUIREMENTS
        assert "keyhole deregister" in COMMAND_REQUIREMENTS
        reqs = COMMAND_REQUIREMENTS["keyhole deregister"]
        assert "authenticated_identity" in reqs
        assert "run_dispatch" in reqs

    def test_deregister_has_optional_surfaces(self):
        from keyhole_sdk.negotiation.evaluator import COMMAND_OPTIONAL_SURFACES
        assert "keyhole deregister" in COMMAND_OPTIONAL_SURFACES
        opts = COMMAND_OPTIONAL_SURFACES["keyhole deregister"]
        assert "explainability" in opts
        assert "support_bundle" in opts

    def test_deregister_blocked_without_auth(self):
        from keyhole_sdk.negotiation.evaluator import evaluate_command
        from keyhole_sdk.negotiation.models import NegotiatedFeatures, CommandStatus

        features = NegotiatedFeatures(
            authenticated_identity=False,
            run_dispatch=True,
        )
        result = evaluate_command("keyhole deregister", features)
        assert result.status == CommandStatus.BLOCKED

    def test_deregister_blocked_without_run_dispatch(self):
        from keyhole_sdk.negotiation.evaluator import evaluate_command
        from keyhole_sdk.negotiation.models import NegotiatedFeatures, CommandStatus

        features = NegotiatedFeatures(
            authenticated_identity=True,
            run_dispatch=False,
        )
        result = evaluate_command("keyhole deregister", features)
        assert result.status == CommandStatus.BLOCKED

    def test_deregister_allowed_with_all_surfaces(self):
        from keyhole_sdk.negotiation.evaluator import evaluate_command
        from keyhole_sdk.negotiation.models import NegotiatedFeatures, CommandStatus

        features = NegotiatedFeatures(
            authenticated_identity=True,
            run_dispatch=True,
            explainability=True,
            support_bundle=True,
        )
        result = evaluate_command("keyhole deregister", features)
        assert result.status == CommandStatus.ALLOWED

    def test_deregister_degraded_without_optional(self):
        from keyhole_sdk.negotiation.evaluator import evaluate_command
        from keyhole_sdk.negotiation.models import NegotiatedFeatures, CommandStatus

        features = NegotiatedFeatures(
            authenticated_identity=True,
            run_dispatch=True,
            explainability=False,
            support_bundle=False,
        )
        result = evaluate_command("keyhole deregister", features)
        assert result.status == CommandStatus.DEGRADED


# --------------------------------------------------------------
# Operation registry - auth.remove registered
# --------------------------------------------------------------


class TestDeregisterOperationRegistry:
    """auth.remove is registered in the operation registry."""

    def test_auth_remove_registered(self):
        from keyhole_sdk.transport.operation_registry import is_registered
        assert is_registered("auth.remove")

    def test_auth_remove_requires_idempotency(self):
        from keyhole_sdk.transport.operation_registry import requires_idempotency
        assert requires_idempotency("auth.remove")

    def test_auth_remove_is_write_operation(self):
        from keyhole_sdk.transport.operation_registry import (
            get_operation,
            OperationClass,
        )
        op = get_operation("auth.remove")
        assert op is not None
        assert op.operation_class == OperationClass.WRITE_IDEMPOTENT_REQUIRED

    def test_auth_remove_requires_proof(self):
        from keyhole_sdk.transport.operation_registry import get_operation
        op = get_operation("auth.remove")
        assert op is not None
        assert op.proof_required is True


# --------------------------------------------------------------
# SDK public surface - imports work
# --------------------------------------------------------------


class TestDeregisterSDKExports:
    """SDK-CLIENT-22 exports are accessible from keyhole_sdk."""

    def test_import_client(self):
        from keyhole_sdk import DeregistrationClient
        assert DeregistrationClient is not None

    def test_import_models(self):
        from keyhole_sdk import (
            DeregistrationOutcome,
            DeregistrationRequest,
            DeregistrationStatus,
        )
        assert DeregistrationRequest is not None
        assert DeregistrationOutcome is not None
        assert DeregistrationStatus is not None

    def test_import_proof(self):
        from keyhole_sdk import DeregistrationProofBundle
        assert DeregistrationProofBundle is not None

    def test_import_errors(self):
        from keyhole_sdk import (
            DeregistrationError,
            DeregistrationAlreadyDeletedError,
            DeregistrationNetworkError,
            DeregistrationNotAuthenticatedError,
            DeregistrationOwnershipMismatchError,
            DeregistrationPolicyBlockedError,
            DeregistrationSurfaceUnavailableError,
        )
        assert DeregistrationError is not None
        assert DeregistrationAlreadyDeletedError is not None

    def test_all_exports_in_all(self):
        import keyhole_sdk
        expected = [
            "DeregistrationClient",
            "DeregistrationProofBundle",
            "DeregistrationOutcome",
            "DeregistrationRequest",
            "DeregistrationStatus",
            "DeregistrationError",
            "DeregistrationAlreadyDeletedError",
            "DeregistrationNetworkError",
            "DeregistrationNotAuthenticatedError",
            "DeregistrationOwnershipMismatchError",
            "DeregistrationPolicyBlockedError",
            "DeregistrationSurfaceUnavailableError",
        ]
        for name in expected:
            assert name in keyhole_sdk.__all__, f"{name} missing from __all__"


# --------------------------------------------------------------
# Repair guidance tests - section19
# --------------------------------------------------------------


class TestRepairGuidance:
    """Every failure class maps to deterministic repair guidance - section19."""

    repair_map = {
        "not_authenticated": "keyhole login",
        "ownership_mismatch": "account owner",
        "surface_unavailable": "boundary",
        "already_deleted": "prior",
        "policy_blocked": "support",
        "network_error": "network",
    }

    def test_not_authenticated_repair(self):
        err = DeregistrationNotAuthenticatedError()
        assert any("login" in s.lower() for s in err.repair_suggestions)

    def test_ownership_mismatch_repair(self):
        err = DeregistrationOwnershipMismatchError()
        assert any("owner" in s.lower() for s in err.repair_suggestions)

    def test_surface_unavailable_repair(self):
        err = DeregistrationSurfaceUnavailableError()
        assert any("boundary" in s.lower() for s in err.repair_suggestions)

    def test_already_deleted_repair(self):
        err = DeregistrationAlreadyDeletedError()
        assert any("prior" in s.lower() for s in err.repair_suggestions)

    def test_policy_blocked_repair(self):
        err = DeregistrationPolicyBlockedError()
        assert any("support" in s.lower() for s in err.repair_suggestions)

    def test_network_error_repair(self):
        err = DeregistrationNetworkError()
        assert any("network" in s.lower() for s in err.repair_suggestions)
